// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVZ8vLqGxKxQxKxQxKxQxKxQxKxQxKxQ',
    appId: '1:123456789:web:abcdefabcdefabcd',
    messagingSenderId: '123456789',
    projectId: 'yusufusta-3db28',
    authDomain: 'yusufusta-3db28.firebaseapp.com',
    storageBucket: 'yusufusta-3db28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyFT3nu36rpwwLhtN0KHT6R323Bbf2iQ',
    appId: '1:661419486599:android:47d0b16613da7c3e49f722',
    messagingSenderId: '661419486599',
    projectId: 'yusufusta-3db28',
    storageBucket: 'yusufusta-3db28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVZ8vLqGxKxQxKxQxKxQxKxQxKxQxKxQ',
    appId: '1:123456789:ios:abcdefabcdefabcd',
    messagingSenderId: '123456789',
    projectId: 'yusufusta-3db28',
    storageBucket: 'yusufusta-3db28.appspot.com',
    iosBundleId: 'com.example.habermerkezim1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVZ8vLqGxKxQxKxQxKxQxKxQxKxQxKxQ',
    appId: '1:123456789:ios:abcdefabcdefabcd',
    messagingSenderId: '123456789',
    projectId: 'yusufusta-3db28',
    storageBucket: 'yusufusta-3db28.appspot.com',
    iosBundleId: 'com.example.habermerkezim1',
  );
}